# Generated by Django 4.1.13 on 2025-01-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('nombre_padre', models.CharField(max_length=100)),
                ('nombre_madre', models.CharField(max_length=100)),
                ('grado', models.IntegerField()),
                ('seccion', models.CharField(max_length=1)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
